'use client';

import Link from 'next/link';
import { ArrowDown, ArrowRight, Braces, Check, CornerDownRight, ScanLine, Trophy } from 'lucide-react';
import { motion } from 'framer-motion';
import { rounds, rules } from '@/lib/mock-data';
import { PublicLayout } from '@/components/layout/PublicLayout';
import { PageIntro } from '@/components/ui';

const reveal = { initial:{opacity:0,y:24}, whileInView:{opacity:1,y:0}, viewport:{once:true,amount:.18}, transition:{duration:.65,ease:[.16,1,.3,1] as const} };

function EngineVisual() { return <div className="engine-wrap" aria-label="Prompt engine visualization">
  <div className="engine-index">PROMPT_ENGINE / 01</div><div className="engine-window"><div className="engine-bar"><span/><span/><b>PRECISION SYSTEM</b><em>LIVE</em></div><div className="engine-grid"><div className="engine-code"><p><i>01</i><span className="dim">role</span>: prompt_engineer</p><p><i>02</i><span className="dim">objective</span>: solve</p><p><i>03</i><span className="dim">constraints</span>: complete</p><p><i>04</i><span className="dim">precision</span>: <b>98.4%</b></p></div><div className="engine-node" aria-hidden="true"><span>P</span><div className="orbit orbit-one"/><div className="orbit orbit-two"/></div></div><div className="analysis-row"><span>ANALYZING INPUT</span><strong>87%</strong></div><div className="progress"><span/></div><div className="engine-output"><span>OUTPUT</span><p>Instruction set resolved. Missing context identified.</p><b>VALIDATED ✓</b></div></div><div className="axis"><span>CONTEXT</span><span>CONSTRAINT</span><span>OUTPUT</span></div>
  </div>;
}

function RoundEditorial({ round, compact = false }: { round: typeof rounds[number]; compact?: boolean }) { return <motion.article className={`round-editorial ${compact?'compact':''}`} {...reveal}>
  <div className="round-num">{round.code}</div><div className="round-rule"/><div className="round-copy"><p className="eyebrow">ROUND {round.code} / CORE CHALLENGE</p><h3>{round.title}</h3><blockquote>“{round.prompt}”</blockquote><p>{round.description}</p><div className="skill-list">{round.skills.map(skill=><span key={skill}>{skill}</span>)}</div><small>EVALUATION / {round.evaluation}</small></div>
  </motion.article>;
}

export function HomePage() { return <PublicLayout><main>
  <section className="hero" aria-labelledby="hero-title"><motion.div className="hero-copy" initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{duration:.8,ease:[.16,1,.3,1]}}><p className="eyebrow"><span>&gt;</span> PROMPTHON 2026 / SYSTEM INITIALIZED</p><h1 id="hero-title"><span>PROMPTHON</span><strong>AI PROMPT<br/>ENGINEERING<br/>HACKATHON</strong></h1><p className="hero-intro">Turn vague problems into precise instructions.<br/>Reverse-engineer intelligence. Recreate the impossible.</p><div className="hero-meta"><p><span>DATE / TIME</span>12 SEP 2026 · 09:00—16:00</p><p><span>TEAM / ENTRY</span>1—3 MEMBERS · ₹100</p></div><div className="hero-actions"><Link className="primary-button" href="/login">Participant login <ArrowRight size={17}/></Link><a className="text-link" href="#challenge">Explore the challenge <ArrowDown size={15}/></a></div></motion.div><motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} transition={{delay:.15,duration:.9,ease:[.16,1,.3,1]}}><EngineVisual/></motion.div></section>
  <div className="hero-rail" aria-hidden="true"><span>12 / 09 / 26</span><i/><span>CSBS · EEC</span></div>
  <motion.section className="intro-section editorial-section" {...reveal}><div className="section-index">01</div><div><p className="eyebrow"><span>01 / </span>WHAT IS PROMPTHON?</p><h2>Beyond asking.<br/>Into engineering.</h2></div><div className="intro-copy"><p className="large-copy">Prompthon is an AI prompt engineering challenge where participants learn to think beyond simply asking AI questions.</p><p>Competitors discover missing information, formulate precise prompts, reverse-engineer outputs and translate visual observations into structured instructions.</p><div className="code-note"><Braces size={18}/><span>clarity + context + constraints = precision</span></div></div></motion.section>
  <section id="challenge" className="rounds-section"><header className="section-heading"><p className="eyebrow"><span>02 / </span>THE CHALLENGE</p><h2>Three rounds.<br/>Three ways to think.<br/><em>One skill — precision.</em></h2></header>{rounds.map(round=><RoundEditorial round={round} key={round.id}/>)}</section>
  <motion.section className="flow-section editorial-section" {...reveal}><div><p className="eyebrow"><span>03 / </span>HOW IT WORKS</p><h2>Access is earned.<br/>Round by round.</h2><p className="page-copy">Every stage is reviewed. Approval unlocks the next challenge; rejection closes access with clarity.</p></div><div className="flow-track">{['Participant login','Round 01','Submit evidence','Admin review','Approved','Round 02 unlocked','Admin review','Round 03','Final evaluation'].map((step,i)=><div className="flow-step" key={step}><span>{String(i+1).padStart(2,'0')}</span><i/><strong>{step}</strong>{i<8&&<ArrowDown size={13}/>}</div>)}<div className="reject-branch"><CornerDownRight size={16}/><span>REJECTED → ROUND ACCESS ENDS</span></div></div></motion.section>
  <motion.section className="details-section" {...reveal}><p className="eyebrow"><span>04 / </span>EVENT PARAMETERS</p><div className="details-grid">{[['DATE','12 SEP 2026'],['TIME','9:00 AM — 4:00 PM'],['TEAM SIZE','1—3 MEMBERS'],['REGISTRATION FEE','₹100'],['EVENT DURATION','5 HOURS'],['TARGET','GRADES 9—12'],['TOOLS','FREE-TIER AI TOOLS']].map(([k,v])=><div key={k}><span>{k}</span><strong>{v}</strong></div>)}</div></motion.section>
  <PrizeSection/>
  <motion.section className="coordinator-section editorial-section" {...reveal}><div><p className="eyebrow"><span>06 / </span>STUDENT COORDINATORS</p><h2>Direct line<br/>to the event.</h2></div><div className="contact-list"><a href="tel:+919808144754"><span>Karthick Vamsi</span><strong>98081 44754</strong></a><a href="tel:+919445423155"><span>Hemachandran</span><strong>94454 23155</strong></a></div></motion.section>
  <FinalCta/>
  </main></PublicLayout>; }

function PrizeSection(){ return <motion.section className="prize-section" {...reveal}><p className="eyebrow"><span>05 / </span>PRIZE SYSTEM</p><div className="prize-stage"><Trophy size={22}/>{[['02','₹2000','SECOND PLACE'],['01','₹3000','FIRST PLACE'],['03','₹1000','THIRD PLACE']].map(([n,p,l])=><div className={`prize prize-${n}`} key={n}><span>{n}</span><strong>{p}</strong><p>{l}</p></div>)}</div></motion.section>; }
function FinalCta(){ return <section className="final-cta"><div className="scanline"><ScanLine/></div><p className="eyebrow">&gt; AWAITING INPUT_</p><h2>THINK LIKE A HACKER.<br/><span>PROMPT LIKE A PRO.</span></h2><p>Your challenge begins with a blank input.</p><Link className="primary-button" href="/login">Participant login <ArrowRight size={17}/></Link></section>; }

export function AboutPage(){ return <PublicLayout><main className="public-page"><PageIntro index="01" eyebrow="ABOUT THE SYSTEM" title="Precision is not a feature. It is the discipline." copy="PROMPTHON 2026 is an official technical event created by the Department of Computer Science and Business Systems, Easwari Engineering College."/><section className="manifesto-grid"><motion.div {...reveal}><p className="big-statement">AI is only as useful as the thinking that directs it.</p></motion.div><motion.div className="prose" {...reveal}><p>Prompthon asks participants to move past casual prompting and work like engineers: uncover ambiguity, define constraints, test assumptions and communicate intent with clarity.</p><p>The competition is designed for students in Grades 9—12 and rewards thoughtful iteration over lucky output.</p></motion.div></section><section className="principles"><p className="eyebrow">COMPETITION PRINCIPLES</p>{[['01','Discover before directing'],['02','Make constraints explicit'],['03','Prove every result'],['04','Optimize for useful output']].map(([n,t])=><div key={n}><span>{n}</span><h3>{t}</h3><Check size={18}/></div>)}</section><section className="institution-block"><div><p className="eyebrow">ORGANIZED BY</p><h2>Department of Computer Science<br/>and Business Systems</h2></div><p>Easwari Engineering College<br/>12 September 2026</p></section></main></PublicLayout>; }

export function RoundsPage(){ return <PublicLayout><main className="public-page"><PageIntro index="02" eyebrow="THE CHALLENGE" title="Three tests of exact thinking." copy="Each round isolates a different prompt-engineering skill. Progression is controlled by organizer review."/><section className="rounds-page-list">{rounds.map(round=><RoundEditorial round={round} compact key={round.id}/>)}</section><section className="qualification-flow"><p className="eyebrow">QUALIFICATION LOGIC</p><div><span>ROUND 01</span><ArrowRight/><span>ADMIN REVIEW</span><ArrowRight/><span className="accent">APPROVED</span><ArrowRight/><span>ROUND 02 UNLOCKED</span></div><div className="muted-path"><span>REJECTED</span><ArrowRight/><span>COMPETITION ENDS FOR TEAM</span></div></section></main></PublicLayout>; }

export function RulesPage(){ return <PublicLayout><main className="public-page"><PageIntro index="03" eyebrow="RULES & GUIDELINES" title="Clear constraints. Fair evaluation." copy="The operating principles that keep every round focused, comparable and transparent."/><section className="rules-list">{rules.map(([n,title,copy])=><motion.article key={n} {...reveal}><span>{n}</span><h2>{title}</h2><p>{copy}</p></motion.article>)}</section><section className="rules-note"><p className="eyebrow">FINAL AUTHORITY</p><h2>The decision of the organizers and judges is final and binding.</h2></section></main></PublicLayout>; }

export function PrizesPage(){ return <PublicLayout><main className="public-page"><PageIntro index="04" eyebrow="PRIZES" title="Precision, recognized." copy="Three placements. One shared standard: exceptional command of context, structure and intent."/><PrizeSection/><section className="evaluation-matrix"><p className="eyebrow">EVALUATION LENS</p>{rounds.map(r=><div key={r.id}><span>ROUND {r.code}</span><strong>{r.title}</strong><p>{r.evaluation}</p></div>)}</section><FinalCta/></main></PublicLayout>; }
