'use client';
import Link from 'next/link';
import { Award, Check, CheckCircle2, Download, FileText, KeyRound, LoaderCircle, Lock, Mail, ShieldCheck, Trophy, UserRound, X } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { useRouter } from 'next/navigation';
import { FormEvent, useCallback, useEffect, useState } from 'react';
import { ApiClientError, participantApi, ParticipantOverview } from '@/services/api-client';
import { PortalLayout } from '@/components/layout/PortalLayout';
import { PageIntro, StatusBadge } from '@/components/ui';

export function ParticipantLogin(){const router=useRouter();const[email,setEmail]=useState('');const[teamCode,setTeamCode]=useState('');const[step,setStep]=useState<'email'|'team'|'success'>('email');const[loading,setLoading]=useState(false);const[error,setError]=useState(()=>typeof window!=='undefined'&&new URLSearchParams(window.location.search).get('reason')==='session-replaced'?'Your account was signed in on another device.':'');
  async function verifyEmail(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{const normalized=email.trim().toLowerCase();const result=await participantApi.verifyEmail(normalized);if(!result.eligible)throw new Error('This email is not on the admitted participant list.');setEmail(normalized);setStep('team')}catch(reason){setError(reason instanceof Error?reason.message:'Verification failed.')}finally{setLoading(false)}}
  async function login(e:FormEvent){e.preventDefault();setLoading(true);setError('');try{const result=await participantApi.login(email,teamCode);setStep('success');router.replace(result.teamDetailsRequired?'/team-setup':'/dashboard')}catch(reason){setError(reason instanceof Error?reason.message:'Login failed.')}finally{setLoading(false)}}
  return <main className="auth-page"><Link className="wordmark auth-wordmark" href="/"><span className="brand-mark">P</span><span>PROMPTHON</span></Link><div className="auth-grid"><section className="auth-copy"><p className="eyebrow"><span>&gt;</span> VERIFIED PARTICIPANT GATE</p><h1>Enter the<br/><span>challenge.</span></h1><p>Access the live competition workspace, round briefs and submission system.</p><div className="auth-system"><span><i/>EVENT SYSTEM</span><strong>ONLINE</strong></div></section><motion.section className="auth-panel participant-auth-panel" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}><p className="eyebrow">PARTICIPANT ACCESS / {step==='email'?'01':'02'}</p><AnimatePresence mode="wait" initial={false}>{step==='email'&&<motion.div className="auth-step" key="email" initial={{opacity:0}} animate={{opacity:1}}><h2>Welcome back.</h2><p>Enter your registered email to verify admission.</p><form onSubmit={verifyEmail}><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required disabled={loading}/></label>{error&&<p className="form-error">{error}</p>}<button className="button primary wide" disabled={loading}>{loading?'VERIFYING…':'VERIFY EMAIL →'}</button></form></motion.div>}{step==='team'&&<motion.div className="auth-step" key="team" initial={{opacity:0}} animate={{opacity:1}}><h2>Join your team.</h2><p>Your email is verified. Enter the organizer-issued Team Code.</p><div className="verified-email"><CheckCircle2 size={16}/><div><span>VERIFIED EMAIL</span><strong>{email}</strong></div><button type="button" onClick={()=>setStep('email')}>CHANGE</button></div><form onSubmit={login}><label>Team code<div className="team-code-input"><KeyRound size={16}/><input value={teamCode} onChange={e=>setTeamCode(e.target.value.toUpperCase())} required/></div></label>{error&&<p className="form-error">{error}</p>}<button className="button primary wide" disabled={loading}>{loading?'AUTHENTICATING…':'ENTER TEAM WORKSPACE →'}</button></form></motion.div>}{step==='success'&&<motion.div className="auth-step auth-success" key="success" initial={{opacity:0}} animate={{opacity:1}}><span><Check size={24}/></span><h2>Team verified.</h2><p>Opening your database-backed workspace.</p></motion.div>}</AnimatePresence>{step!=='success'&&<Link className="admin-entry" href="/admin/login"><ShieldCheck size={14}/>Organizer access</Link>}</motion.section></div></main>}

function useOverview(){const[data,setData]=useState<ParticipantOverview|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);const load=useCallback(()=>participantApi.getOverview().then(setData).catch(reason=>setError(reason instanceof ApiClientError&&reason.status===401?'Participant login is required.':reason instanceof Error?reason.message:'Could not load your record.')).finally(()=>setLoading(false)),[]);useEffect(()=>{void load()},[load]);return{data,error,loading}}
function State({loading,error}:{loading:boolean;error:string}){if(loading)return <div className="portal-loading"><LoaderCircle className="spin"/>Loading…</div>;if(error)return <div className="portal-error"><X/>{error}<Link href="/login">Login</Link></div>;return null}

export function ParticipantSubmissions(){const{data,error,loading}=useOverview();return <PortalLayout><div className="portal-content"><PageIntro eyebrow="SUBMISSION ARCHIVE" title="Your competition record." copy="Every status and decision below is loaded from PostgreSQL."/><State loading={loading} error={error}/>{data&&<section className="participant-submissions">{data.rounds.map(round=><article className={round.submission?'':'locked-record'} key={round.id}><div><span>ROUND 0{round.number}</span><StatusBadge status={round.submission?.status.replaceAll('_',' ')||round.accessStatus.replaceAll('_',' ')}/></div><h2>{round.title}</h2><p>{round.submission?.submittedAt?new Date(round.submission.submittedAt).toLocaleString('en-IN'):'No submission recorded for this round.'}</p>{round.submission?.evaluation&&<aside className={round.submission.evaluation.decision==='APPROVED'?'':'review'}>{round.submission.evaluation.decision==='APPROVED'?<Check/>:<X/>}<div><strong>{round.submission.evaluation.decision}</strong><p>{round.submission.evaluation.decision==='APPROVED'?'Eligibility for the next round has been granted.':'Later rounds remain inaccessible.'}</p></div></aside>}</article>)}</section>}</div></PortalLayout>}

export function ProfilePage(){const{data,error,loading}=useOverview();return <PortalLayout><div className="portal-content"><PageIntro eyebrow="PARTICIPANT PROFILE" title={data?.participant.name||'Verified identity'} copy="Profile data is managed by the organizers."/><State loading={loading} error={error}/>{data&&<section className="profile-layout"><div className="profile-avatar">{data.participant.name.split(/\s+/).map(v=>v[0]).slice(0,2).join('')}</div><div className="profile-fields"><div><span>EMAIL</span><strong>{data.participant.email}</strong><Mail size={16}/></div><div><span>TEAM CODE</span><strong>{data.team.code}</strong><UserRound size={16}/></div><div><span>TEAM MEMBERS</span><strong>{data.team.members.length}</strong><ShieldCheck size={16}/></div><div><span>ACCOUNT STATUS</span><strong>{data.participant.status}</strong><FileText size={16}/></div></div></section>}</div></PortalLayout>}

export function CertificatePage(){const[data,setData]=useState<Awaited<ReturnType<typeof participantApi.getCertificates>>|null>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(true);useEffect(()=>{participantApi.getCertificates().then(setData).catch(reason=>setError(reason instanceof Error?reason.message:'Certificates are unavailable.')).finally(()=>setLoading(false))},[]);return <PortalLayout><div className="portal-content certificate-page"><PageIntro eyebrow="PARTICIPATION RECORD" title="Certificates." copy="Your individual PROMPTHON 2026 participation certificates are securely issued to your team."/><State loading={loading} error={error}/>{data&&!data.eligible&&<section className="certificate-locked"><Lock/><div><span>CERTIFICATES / LOCKED</span><h2>Your event participation is still active.</h2><p>Your participation certificate will become available when your event participation is complete.</p></div></section>}{data&&data.eligible&&data.status!=='READY'&&<section className="certificate-locked preparing"><Award/><div><span>CERTIFICATES / {data.status}</span><h2>Your certificates are being prepared.</h2><p>Please check again shortly. No action is required from your team.</p></div></section>}{data?.status==='READY'&&<><section className="certificate-ready-head"><div><span>CERTIFICATES / READY</span><h2>Your PROMPTHON 2026 certificates are ready.</h2></div><a className="button primary" href={participantApi.certificateZipUrl()}><Download/>Download all certificates</a></section><section className="certificate-list">{data.certificates.map((certificate,index)=><article key={certificate.id}><span>MEMBER {String(index+1).padStart(2,'0')}</span><Award/><div><h3>{certificate.memberName}</h3><p>{certificate.certificateCode}</p></div><a className="button secondary" href={participantApi.certificateUrl(certificate.id)}><Download/>Download certificate</a></article>)}</section></>}</div></PortalLayout>}

export function LeaderboardPage(){const[rows,setRows]=useState<Array<{teamId:string;teamCode:string;score:number;rounds:number}>>([]);const[error,setError]=useState('');const[loading,setLoading]=useState(true);useEffect(()=>{participantApi.getLeaderboard().then(setRows).catch(reason=>setError(reason instanceof Error?reason.message:'Leaderboard unavailable.')).finally(()=>setLoading(false))},[]);return <PortalLayout><div className="portal-content"><PageIntro eyebrow="LIVE STANDINGS" title="Leaderboard." copy="Scores reflect finalized administrator evaluations."/><State loading={loading} error={error}/>{!loading&&!error&&<section className="leaderboard-panel"><header><span>POSITION</span><span>TEAM CODE</span><span>ROUNDS</span><span>SCORE</span></header>{rows.map((row,index)=><div key={row.teamId}><strong>{String(index+1).padStart(2,'0')}</strong><span>{row.teamCode}<small>QUALIFIED TEAM</small></span><span>{String(row.rounds).padStart(2,'0')}</span><b>{row.score}</b></div>)}</section>}<p className="leaderboard-note"><Trophy size={14}/>Only persisted evaluation scores are included.</p></div></PortalLayout>}
