'use client';

import Link from 'next/link';
import { ArrowRight, Check, Clock3, FileText, Lock, Mail, ShieldCheck, UserRound, X } from 'lucide-react';
import { motion } from 'framer-motion';
import { useRouter } from 'next/navigation';
import { FormEvent, useState } from 'react';
import { currentTeam, generatedOutput, roundOneChallenge, rounds } from '@/lib/mock-data';
import { authService, submissionService } from '@/services/mock-services';
import { PortalLayout } from '@/components/layout/PortalLayout';
import { FileDrop, PageIntro, StatusBadge } from '@/components/ui';

type DemoState = 'EVENT NOT STARTED'|'ROUND ACTIVE'|'SUBMITTED'|'UNDER REVIEW'|'APPROVED'|'REJECTED'|'NEXT ROUND UNLOCKED'|'EVENT ENDED';
const stateInfo: Record<DemoState,{title:string;copy:string;tone:string}> = {
  'EVENT NOT STARTED':{title:'Briefing window',copy:'The event has not started. Your team access is ready.',tone:'muted'},
  'ROUND ACTIVE':{title:'Round 02 · Output → Prompt',copy:'The challenge is live. Submit before the round closes.',tone:'live'},
  'SUBMITTED':{title:'Submission received',copy:'Your work is saved and editing is now disabled.',tone:'submitted'},
  'UNDER REVIEW':{title:'Review in progress',copy:'The organizers are evaluating your latest submission.',tone:'review'},
  'APPROVED':{title:'Round approved',copy:'Your result meets the qualification standard.',tone:'approved'},
  'REJECTED':{title:'Access concluded',copy:'This round was not approved. Feedback remains available below.',tone:'rejected'},
  'NEXT ROUND UNLOCKED':{title:'Round 02 unlocked',copy:'Your team is qualified. The next brief is ready.',tone:'unlocked'},
  'EVENT ENDED':{title:'Prompthon 2026 · Event ended',copy:'Thank you for participating in the challenge. Your workspace is now read-only.',tone:'ended'},
};

export function ParticipantLogin(){ const router=useRouter(); const [email,setEmail]=useState('team.alpha@example.com'); const [state,setState]=useState<'idle'|'loading'|'success'>('idle'); const [error,setError]=useState('');
  async function submit(e:FormEvent){e.preventDefault();setError('');if(!email.includes('@')){setError('Enter the admitted email address used for your team.');return;}setState('loading');const result=await authService.participantLogin(email);if(result.ok){setState('success');setTimeout(()=>router.push('/dashboard'),500);}}
  return <main className="auth-page"><Link className="wordmark auth-wordmark" href="/"><span className="brand-mark">P</span><span>PROMPTHON</span></Link><div className="auth-grid"><section className="auth-copy"><p className="eyebrow"><span>&gt;</span> VERIFIED PARTICIPANT GATE</p><h1>Enter the<br/><span>challenge.</span></h1><p>Access the live competition workspace, round briefs and submission system.</p><div className="auth-system"><span><i/>EVENT SYSTEM</span><strong>ONLINE</strong></div></section><motion.section className="auth-panel" initial={{opacity:0,y:18}} animate={{opacity:1,y:0}}><p className="eyebrow">PARTICIPANT ACCESS / 01</p><h2>Welcome back.</h2><p>Enter your registered email to continue.</p><form onSubmit={submit}><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="email@example.com" autoComplete="email"/></label>{error&&<p className="form-error">{error}</p>}<button className="button primary wide" disabled={state!=='idle'}>{state==='loading'?'VALIDATING ACCESS...':state==='success'?'ACCESS VERIFIED ✓':'CONTINUE →'}</button></form><small>Access is available only to participants admitted by the organizers.</small><Link className="admin-entry" href="/admin/login"><ShieldCheck size={14}/>Organizer access</Link></motion.section></div></main>;
}

export function DashboardPage(){const [demo,setDemo]=useState<DemoState>('ROUND ACTIVE');const info=stateInfo[demo];return <PortalLayout><div className="portal-content"><PageIntro eyebrow="TEAM WORKSPACE" title="Welcome back, Team Alpha." action={<div className="team-id"><span>TEAM ID</span><strong>{currentTeam.id}</strong></div>}/><section className={`current-state state-${info.tone}`}><div className="state-head"><StatusBadge status={demo}/><span>EVENT STATUS · LIVE</span></div><p className="eyebrow">CURRENT SYSTEM STATE</p><h2>{info.title}</h2><p>{info.copy}</p><div className="state-actions">{!['EVENT NOT STARTED','UNDER REVIEW','REJECTED','EVENT ENDED'].includes(demo)&&<Link className="button primary" href="/round/2">Enter round <ArrowRight size={16}/></Link>}<span className="timer"><Clock3 size={15}/>02:14:32 REMAINING</span></div></section><RoundProgress/><section className="dashboard-grid"><article><p className="eyebrow">TEAM SIGNAL</p><div className="metric-line"><strong>03</strong><span>ACTIVE<br/>MEMBERS</span></div><Link href="/team">View team <ArrowRight size={14}/></Link></article><article><p className="eyebrow">LATEST SUBMISSION</p><StatusBadge status="Approved"/><h3>Round 01 · Vague → Precise</h3><Link href="/submissions">View record <ArrowRight size={14}/></Link></article></section><section className="state-lab"><div><p className="eyebrow">INTERFACE STATE PREVIEW</p><h2>Event-state system</h2><p>Frontend simulation for organizer-controlled competition states.</p></div><label>Preview state<select value={demo} onChange={e=>setDemo(e.target.value as DemoState)}>{Object.keys(stateInfo).map(s=><option key={s}>{s}</option>)}</select></label></section></div></PortalLayout>}

function RoundProgress(){return <section className="round-progress"><p className="eyebrow">QUALIFICATION PROGRESS</p><div>{rounds.map((round,i)=><div className={`progress-item ${i===0?'done':i===1?'active':'locked'}`} key={round.id}><span>{i===0?<Check/>:i===2?<Lock/>:<i/>}</span><div><small>ROUND {round.code}</small><strong>{round.title}</strong><p>{i===0?'COMPLETED':i===1?'ACTIVE':'LOCKED'}</p></div>{i<2&&<b/>}</div>)}</div></section>}

export function TeamPage(){return <PortalLayout><div className="portal-content"><PageIntro eyebrow="TEAM PROFILE" title="Team Alpha" copy="A three-person competition unit. Team membership is organizer-verified and read-only." action={<StatusBadge status="Active"/>}/><section className="team-banner"><div><span>TEAM ID</span><strong>{currentTeam.id}</strong></div><div><span>CURRENT ROUND</span><strong>ROUND 02</strong></div><div><span>STATUS</span><strong>ACTIVE</strong></div></section><section className="member-list"><p className="eyebrow">TEAM MEMBERS / 03</p>{currentTeam.members.map((member,i)=><article key={member.email}><span>0{i+1}</span><div><h2>{member.name}</h2><p>{member.role}</p></div><div><small>EMAIL</small><p>{member.email}</p></div><div><small>ACADEMIC</small><p>{member.year} · {member.department}</p></div></article>)}</section></div></PortalLayout>}

export function RoundPage({roundId}:{roundId:number}){const round=rounds[roundId-1];const locked=roundId===3;const [files,setFiles]=useState<Record<string,string>>({});const [submitted,setSubmitted]=useState(false);const [submitting,setSubmitting]=useState(false);const [prompt,setPrompt]=useState('');const [output,setOutput]=useState('');
  async function submit(e:FormEvent){e.preventDefault();setSubmitting(true);await submissionService.submit(roundId);setSubmitting(false);setSubmitted(true);window.scrollTo({top:0,behavior:'smooth'});}
  if(locked)return <PortalLayout><div className="portal-content"><PageIntro eyebrow={`ROUND ${round.code}`} title={round.title}/><section className="locked-round"><Lock size={28}/><p className="eyebrow">QUALIFICATION REQUIRED</p><h2>Round 03 is locked.</h2><p>Your team must be approved in Round 02 before this challenge becomes available.</p><RoundProgress/><Link className="button secondary" href="/dashboard">Return to dashboard</Link></section></div></PortalLayout>;
  if(submitted)return <PortalLayout><div className="portal-content"><section className="submission-receipt"><div className="receipt-check"><Check/></div><p className="eyebrow">SUBMISSION RECEIVED</p><h1>Round {round.code}</h1><StatusBadge status="Under Review"/><p>Your submission has been received and is currently being reviewed by the organizers.</p><div><span>SUBMITTED</span><strong>12 Sep 2026 · 11:42 AM</strong></div><div className="receipt-actions"><Link className="button secondary" href="/submissions">View submissions</Link><Link className="button primary" href="/dashboard">Dashboard</Link></div></section></div></PortalLayout>;
  return <PortalLayout><div className="portal-content round-workspace"><PageIntro eyebrow={`ROUND ${round.code}`} title={round.title} action={<div className="round-timer"><span>TIME REMAINING</span><strong>02:14:32</strong></div>}/><div className="round-status-line"><i/>ROUND IS LIVE <span>Autosaved locally · 12:08 PM</span></div><form onSubmit={submit} className="round-form">{roundId===1?<><section className="challenge-brief"><p className="eyebrow">CHALLENGE BRIEF / CASE 01</p><p>{roundOneChallenge}</p><div><span>OBJECTIVE</span><strong>Transform ambiguity into an executable instruction.</strong></div></section><FormSelect/><FileDrop label="Upload conversation evidence" fileName={files.conversation} onFile={f=>setFiles({...files,conversation:f.name})}/><TextArea label="FINAL PROMPT" value={prompt} onChange={setPrompt} placeholder="Write your complete, production-ready prompt..."/><TextArea label="FINAL AI OUTPUT" value={output} onChange={setOutput} placeholder="Paste the final AI-generated response..."/><FileDrop label="Upload additional screenshot" fileName={files.screenshot} onFile={f=>setFiles({...files,screenshot:f.name})}/></>:<><section className="generated-output"><p className="eyebrow">AI-GENERATED OUTPUT / REFERENCE</p><pre>{generatedOutput}</pre></section><TextArea label="RECONSTRUCTED PROMPT" value={prompt} onChange={setPrompt} placeholder="Reconstruct the precise instruction that could have produced this output..."/><FormSelect/><TextArea label="GENERATED OUTPUT" value={output} onChange={setOutput} placeholder="Paste the output produced by your reconstructed prompt..."/><FileDrop label="Upload conversation evidence" fileName={files.conversation} onFile={f=>setFiles({...files,conversation:f.name})}/></>}<div className="submit-bar"><p><ShieldCheck size={16}/>Submission locks editing and enters organizer review.</p><button className="button primary" disabled={submitting}>{submitting?'SUBMITTING...':'SUBMIT ROUND →'}</button></div></form></div></PortalLayout>}

function FormSelect(){return <label className="field-label">AI TOOL USED<select defaultValue="ChatGPT"><option>ChatGPT</option><option>Gemini</option><option>Claude</option><option>Microsoft Copilot</option><option>Other free-tier tool</option></select></label>}
function TextArea({label,value,onChange,placeholder}:{label:string;value:string;onChange:(s:string)=>void;placeholder:string}){return <label className="field-label">{label}<textarea value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/><span className="character-count">{value.length} CHARACTERS</span></label>}

export function RoundThreePage(){const [files,setFiles]=useState<Record<string,string>>({});const [prompt,setPrompt]=useState('');const [submitted,setSubmitted]=useState(false);if(submitted)return <PortalLayout><div className="portal-content"><section className="submission-receipt"><div className="receipt-check"><Check/></div><p className="eyebrow">SUBMISSION RECEIVED</p><h1>Round 03</h1><StatusBadge status="Under Review"/><p>Your final visual reconstruction has entered organizer review.</p><Link className="button primary" href="/dashboard">Return to dashboard</Link></section></div></PortalLayout>;return <PortalLayout><div className="portal-content round-workspace"><PageIntro eyebrow="ROUND 03" title="IMAGE → PROMPT" action={<div className="round-timer"><span>TIME REMAINING</span><strong>01:42:08</strong></div>}/><form className="round-form" onSubmit={e=>{e.preventDefault();setSubmitted(true)}}><section className="reference-image"><div className="image-scene"><div className="scene-sun"/><div className="scene-block block-a"/><div className="scene-block block-b"/><div className="scene-line"/></div><div><p className="eyebrow">REFERENCE IMAGE / VISUAL 03</p><h2>Observe every relationship.</h2><p>Translate objects, light, spatial structure and composition into one exact image prompt.</p></div></section><FileDrop label="Upload your generated image" fileName={files.image} onFile={f=>setFiles({...files,image:f.name})}/><TextArea label="IMAGE PROMPT" value={prompt} onChange={setPrompt} placeholder="Describe the scene, composition, light, palette, materials and camera..."/><FormSelect/><FileDrop label="Upload conversation evidence" fileName={files.conversation} onFile={f=>setFiles({...files,conversation:f.name})}/><div className="submit-bar"><p><ShieldCheck size={16}/>This is the final-round submission.</p><button className="button primary">SUBMIT ROUND →</button></div></form></div></PortalLayout>}

export function ParticipantSubmissions(){return <PortalLayout><div className="portal-content"><PageIntro eyebrow="SUBMISSION ARCHIVE" title="Your competition record." copy="Every submitted artifact, review status and organizer decision in one read-only timeline."/><section className="participant-submissions"><article><div><span>ROUND 01</span><StatusBadge status="Approved"/></div><h2>Vague → Precise</h2><p>Submitted 12 Sep 2026 · 11:42 AM</p><div className="submission-files"><span><FileText size={15}/>conversation.pdf</span><span><FileText size={15}/>final-output.txt</span><span><FileText size={15}/>evidence.png</span></div><aside><Check size={18}/><div><strong>ROUND APPROVED</strong><p>Clear constraint discovery and complete final instruction.</p></div></aside></article><article><div><span>ROUND 02</span><StatusBadge status="Under Review"/></div><h2>Output → Prompt</h2><p>Submitted 12 Sep 2026 · 01:08 PM</p><aside className="review"><Clock3 size={18}/><div><strong>ADMIN REVIEW</strong><p>Your submission is locked while evaluation is in progress.</p></div></aside></article><article className="locked-record"><div><span>ROUND 03</span><StatusBadge status="Locked"/></div><h2>Image → Prompt</h2><p>Awaiting Round 02 decision.</p></article></section></div></PortalLayout>}

export function ProfilePage(){return <PortalLayout><div className="portal-content"><PageIntro eyebrow="PARTICIPANT PROFILE" title="Aarav Raman" copy="Verified participant identity. Contact the organizers if a correction is required."/><section className="profile-layout"><div className="profile-avatar">AR</div><div className="profile-fields"><div><span>EMAIL</span><strong>aarav.raman@example.com</strong><Mail size={16}/></div><div><span>TEAM</span><strong>Team Alpha · PRM-1042</strong><UserRound size={16}/></div><div><span>INSTITUTION</span><strong>Greenfield Higher Secondary School</strong><ShieldCheck size={16}/></div><div><span>ACADEMIC</span><strong>Grade 12 · Computer Science</strong><FileText size={16}/></div></div></section><section className="profile-note"><X size={16}/><p>Profile information is managed by the organizers and cannot be edited during the event.</p></section></div></PortalLayout>}
