/* eslint-disable react-hooks/set-state-in-effect -- route loaders synchronize component state with the API */
'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Check, ExternalLink, LoaderCircle, Lock, ShieldCheck, X } from 'lucide-react';
import { ApiClientError, participantApi, ParticipantOverview, ParticipantRoundDetail, ParticipantRoundSummary, RoundAccessStatus } from '@/services/api-client';
import { PortalLayout } from '@/components/layout/PortalLayout';
import { PageIntro, StatusBadge } from '@/components/ui';

type RoundNumber=1|2|3;
const label=(status:RoundAccessStatus)=>status.replaceAll('_',' ').replace(/\b\w/g,char=>char.toUpperCase());

function Failure({message}:{message:string}){return <div className="portal-error" role="alert"><X size={15}/><span>{message}</span>{message.includes('login')&&<Link href="/login">Participant login</Link>}</div>}
function Loading({text='Loading participant workspace…'}:{text?:string}){return <div className="portal-loading"><LoaderCircle className="spin" size={20}/>{text}</div>}

function useOverview(){
  const [data,setData]=useState<ParticipantOverview|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);
  const load=useCallback(()=>participantApi.getOverview().then(setData).catch(reason=>setError(reason instanceof ApiClientError&&reason.status===401?'Participant login is required.':reason instanceof Error?reason.message:'Participant data could not be loaded.')).finally(()=>setLoading(false)),[]);
  useEffect(()=>{void load()},[load]);return{data,error,loading,reload:load};
}

function Progress({rounds}:{rounds:ParticipantRoundSummary[]}){return <section className="qualification-progress"><p className="eyebrow">QUALIFICATION PATH</p><div>{rounds.map((round,index)=><article className={`qualification-step status-${round.accessStatus.toLowerCase()}`} key={round.id}><span>{round.accessStatus==='APPROVED'?<Check size={14}/>:round.accessStatus==='LOCKED'||round.accessStatus==='REJECTED'?<Lock size={13}/>:index+1}</span><div><small>ROUND 0{round.number}</small><strong>{round.title}</strong><p>{label(round.accessStatus)}</p></div>{index<2&&<i/>}</article>)}</div></section>}

export function ParticipantDashboard(){const {data,error,loading}=useOverview();if(loading)return <PortalLayout><div className="portal-content"><Loading/></div></PortalLayout>;if(error||!data)return <PortalLayout><div className="portal-content"><Failure message={error||'Participant workspace is unavailable.'}/></div></PortalLayout>;
  const active=data.rounds.find(round=>round.roundStatus==='LIVE'&&round.contentAvailable);const latest=[...data.rounds].reverse().find(round=>round.accessStatus!=='LOCKED')||data.rounds[0];const current=active||latest;const submitted=data.rounds.filter(round=>round.submission&&round.submission.status!=='DRAFT').length;
  return <PortalLayout><div className="portal-content participant-overview participant-flow-dashboard"><PageIntro eyebrow="PARTICIPANT PORTAL" title={<>Your competition.<br/>Your thinking.<br/><span>Your moment.</span></>} action={<div className="event-live"><i/>{data.event.status}</div>}/><section className="event-identity"><div><span>{data.event.name}</span><strong>AI PROMPT ENGINEERING HACKATHON</strong></div><dl><div><dt>PARTICIPANT</dt><dd>{data.participant.name}</dd></div><div><dt>EMAIL</dt><dd>{data.participant.email}</dd></div><div><dt>TEAM CODE</dt><dd>{data.team.code}</dd></div></dl></section>{current&&<section className={`participant-current-round status-${current.accessStatus.toLowerCase()}`}><div className="current-round-copy"><div className="mission-kicker"><span>CURRENT ACCESS</span><StatusBadge status={label(current.accessStatus)}/></div><span className="mission-number">0{current.number}</span><p>ROUND 0{current.number} / CORE CHALLENGE</p><h2>{current.title}</h2><h3>{current.contentAvailable?'YOUR ROUND WORKSPACE IS OPEN.':current.accessStatus==='REJECTED'?'THIS COMPETITION PATH IS CLOSED.':'AWAITING THE NEXT AUTHORIZED ROUND WINDOW.'}</h3><p className="mission-description">Round access and progress are loaded from the event database. Approval grants eligibility; only an actual submitted response counts as participation.</p><Link className="button primary" href={`/round/${current.number}`}>{current.contentAvailable?'OPEN ACTIVE ROUND':'VIEW ROUND STATUS'} <ArrowRight size={14}/></Link></div><div className="round-gate-readout"><span>{current.contentAvailable?<ShieldCheck/>:<Lock/>}</span><small>DATABASE STATUS</small><strong>{label(current.accessStatus)}</strong><p>{current.roundStatus} ROUND</p></div></section>}<section className="connected-stats">{[[String(submitted).padStart(2,'0'),'YOUR SUBMISSIONS'],[data.team.code,'TEAM IDENTITY'],[current?`0${current.number}`:'—','CURRENT ROUND'],[current?label(current.accessStatus).toUpperCase():'LOCKED','STATUS']].map(([n,l])=><div key={l}><strong>{n}</strong><span>{l}</span></div>)}</section><Progress rounds={data.rounds}/></div></PortalLayout>}

function RoundTabs({rounds,selected,onSelect}:{rounds:ParticipantRoundSummary[];selected:RoundNumber;onSelect:(n:RoundNumber)=>void}){return <div className="participant-round-tabs" role="tablist">{rounds.map(round=><button type="button" role="tab" aria-selected={selected===round.number} className={`${selected===round.number?'selected':''} ${round.contentAvailable?'':'is-locked'}`} onClick={()=>onSelect(round.number as RoundNumber)} key={round.id}><span>0{round.number}</span><strong>ROUND 0{round.number}</strong><small>{!round.contentAvailable&&<Lock size={11}/>} {round.roundStatus==='LIVE'?label(round.accessStatus):round.roundStatus}</small></button>)}</div>}

function RoundPanel({round,onChanged}:{round:ParticipantRoundDetail;onChanged:()=>void}){
  const existing=new Map(round.submission?.answers?.map(answer=>[answer.questionId,answer])||[]);const [aiTool,setAiTool]=useState(round.submission?.aiTool||'Designated AI');const [answers,setAnswers]=useState(()=>round.questions.map(question=>({questionId:question.id,conversationUrl:existing.get(question.id)?.conversationUrl||'',promptText:existing.get(question.id)?.promptText||'',responseText:existing.get(question.id)?.responseText||''})));const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  if(!round.contentAvailable)return <section className="locked-round-rules"><header><div className="lock-emblem"><Lock size={19}/></div><div><p className="eyebrow">ROUND 0{round.number} / ACCESS GATE</p><h2>{round.title}</h2><p>{round.accessStatus==='REJECTED'?'This team did not qualify for this round.':'Rules, questions and submission controls become available only when this round is live and your team is eligible.'}</p></div><StatusBadge status={label(round.accessStatus)}/></header></section>;
  if(round.kind==='PROMPT_REVERSE_ENGINEERING')return <section className="portal-rulebook round-two-offline-brief"><header><div><p className="eyebrow">ROUND 02 / RULES &amp; REGULATIONS</p><h2>{round.title}</h2><p>{round.description}</p></div><StatusBadge status="Offline Evaluation"/></header><div className="round-two-offline-notice"><ShieldCheck size={18}/><div><strong>Paper-and-pen test</strong><p>This round is conducted entirely offline. There are no online questions, answers, or submission controls for participants.</p></div></div><ol>{round.rules.map(rule=><li key={rule.id}><span>{String(rule.position).padStart(2,'0')}</span><p>{rule.text}</p></li>)}</ol></section>;
  const locked=round.submission&&round.submission.status!=='DRAFT';
  async function saveAndSubmit(event:FormEvent){event.preventDefault();setBusy(true);setError('');try{if(round.number===1){if(round.questions.length!==4||answers.length!==4)throw new Error('Round 1 requires all four assigned problems. Refresh the page and try again.');const links=answers.map(answer=>answer.conversationUrl.trim());if(links.some(link=>!link))throw new Error('Add one conversation link for each of the four problems.');if(new Set(links).size!==links.length)throw new Error('Each problem must use a different conversation link. Duplicate links are not allowed.');if(answers.some(answer=>!answer.promptText.trim()))throw new Error('Paste the final prompt for each of the four problems.')}const payload={aiTool,answers:answers.map(answer=>({...answer,conversationUrl:answer.conversationUrl.trim()||undefined,promptText:answer.promptText.trim()})),version:round.submission?.version};await participantApi.saveDraft(round.number,payload);await participantApi.submit(round.number);await onChanged()}catch(reason){setError(reason instanceof Error?reason.message:'Submission failed.');setBusy(false)}}
  if(locked)return <section className="round-one-result"><div className="result-icon"><Check/></div><p className="eyebrow">ROUND 0{round.number} / {round.submission?.status.replaceAll('_',' ')}</p><h2>Submission recorded.</h2><p>This persisted submission is now read-only and available to the administrator review queue.</p>{round.submission?.answers?.map((answer,index)=>answer.conversationUrl&&<a key={answer.questionId} href={answer.conversationUrl} target="_blank" rel="noreferrer">Problem {index+1} conversation <ExternalLink size={12}/></a>)}</section>;
  return <section className="round-one-workspace"><header><div><p className="eyebrow">ROUND 0{round.number} / SUBMISSION FORM</p><h2>{round.title}</h2><p>{round.description}</p></div><StatusBadge status="Round Active"/></header><form className="round-one-form" onSubmit={saveAndSubmit}><label className="portal-field"><span>AI TOOL USED</span><input value={aiTool} onChange={event=>setAiTool(event.target.value)} required/></label><section className="problem-conversation-set"><header><div><span>ASSIGNED QUESTION SET</span><strong>{round.questions.length} database-assigned problem{round.questions.length===1?'':'s'}</strong></div></header><div className="problem-conversation-grid">{round.questions.map((question,index)=><article className="problem-conversation-card" key={question.id}><span>PROBLEM {String(question.position).padStart(2,'0')}</span><strong>{question.title}</strong><p>{question.body}</p><label>CONVERSATION LINK<input type="url" required={round.number===1} value={answers[index]?.conversationUrl||''} onChange={event=>setAnswers(current=>current.map((answer,i)=>i===index?{...answer,conversationUrl:event.target.value}:answer))}/></label>{round.number>1&&<label>FINAL PROMPT<textarea required value={answers[index]?.promptText||''} onChange={event=>setAnswers(current=>current.map((answer,i)=>i===index?{...answer,promptText:event.target.value}:answer))}/></label>}</article>)}</div></section>{error&&<p className="form-error">{error}</p>}<footer><p><ShieldCheck size={15}/>Submission is stored in PostgreSQL and becomes read-only.</p><button className="button primary" disabled={busy}>{busy?'SUBMITTING…':`SUBMIT ROUND 0${round.number} →`}</button></footer></form></section>}

export function ParticipantRoundsFlow({initialRound=1}:{initialRound?:RoundNumber}){const [selected,setSelected]=useState<RoundNumber>(initialRound);const [rounds,setRounds]=useState<ParticipantRoundSummary[]>([]);const [detail,setDetail]=useState<ParticipantRoundDetail|null>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const load=useCallback(async()=>{try{const list=await participantApi.getRounds();setRounds(list);setDetail(await participantApi.getRound(selected));setError('')}catch(reason){setError(reason instanceof ApiClientError&&reason.status===401?'Participant login is required.':reason instanceof Error?reason.message:'Rounds could not be loaded.')}finally{setLoading(false)}},[selected]);useEffect(()=>{void load()},[load]);const choose=(value:RoundNumber)=>{setLoading(true);setSelected(value)};return <PortalLayout><div className="portal-content participant-rounds-flow"><PageIntro eyebrow="PARTICIPANT PORTAL / ROUNDS" title="Competition rounds." copy="Round content, eligibility and submissions come directly from the event database."/>{rounds.length>0&&<RoundTabs rounds={rounds} selected={selected} onSelect={choose}/>} {error?<Failure message={error}/>:loading||!detail?<Loading text="Loading round access…"/>:<RoundPanel key={`${detail.id}-${detail.submission?.version||0}`} round={detail} onChanged={load}/>} {rounds.length>0&&<Progress rounds={rounds}/>}</div></PortalLayout>}

export function ParticipantRulesPage(){const {data,error,loading}=useOverview();const [detail,setDetail]=useState<ParticipantRoundDetail|null>(null);useEffect(()=>{const active=data?.rounds.find(round=>round.roundStatus==='LIVE');if(active)participantApi.getRound(active.number).then(setDetail)},[data]);return <PortalLayout><div className="portal-content participant-rules-page"><PageIntro eyebrow="PARTICIPANT PORTAL / RULEBOOK" title="Rules & regulations." copy="The currently active round's rules are returned by the server."/>{error?<Failure message={error}/>:loading?<Loading/>:!detail?<section className="rules-locked-state"><Lock size={20}/><div><span>RULEBOOK PROTECTED</span><h2>No round is active.</h2><p>Rules appear when an administrator starts the corresponding round.</p></div></section>:<section className="portal-rulebook"><header><div><p className="eyebrow">ROUND 0{detail.number} / RULES & REGULATIONS</p><h2>{detail.title}</h2></div><strong>{String(detail.rules.length).padStart(2,'0')}</strong></header><ol>{detail.rules.map(rule=><li key={rule.id}><span>{String(rule.position).padStart(2,'0')}</span><p>{rule.text}</p></li>)}</ol></section>}</div></PortalLayout>}
